// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PantryPlatoonMVCMain.Data;

#nullable disable

namespace PantryPlatoonMVCMain.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250706180921_AddScheduledPickupToVisit")]
    partial class AddScheduledPickupToVisit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PantryPlatoonMVCMain.Models.AdminReport", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<DateOnly>("Month")
                        .HasColumnType("date");

                    b.Property<int>("RepeatVisitors")
                        .HasColumnType("int");

                    b.Property<int>("TotalItems")
                        .HasColumnType("int");

                    b.Property<int>("TotalStudentsServed")
                        .HasColumnType("int");

                    b.Property<int>("TotalVisits")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalWeight")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("ReportId")
                        .HasName("PK__AdminRep__D5BD48054847CF54");

                    b.ToTable("AdminReports");
                });

            modelBuilder.Entity("PantryPlatoonMVCMain.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("PantryPlatoonMVCMain.Models.Campus", b =>
                {
                    b.Property<int>("CampusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CampusId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CampusName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CampusId")
                        .HasName("PK__Campuses__FD598DD605EAD8FF");

                    b.ToTable("Campus");
                });

            modelBuilder.Entity("PantryPlatoonMVCMain.Models.Donor", b =>
                {
                    b.Property<int>("DonorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DonorId"));

                    b.Property<string>("DonorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DonorId")
                        .HasName("PK__Donor__052E3F78B532FC40");

                    b.ToTable("Donor");
                });

            modelBuilder.Entity("PantryPlatoonMVCMain.Models.DonorSubmission", b =>
                {
                    b.Property<int>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubmissionId"));

                    b.Property<int?>("CampusId")
                        .HasColumnType("int");

                    b.Property<int?>("DonorId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("SubmissionDate")
                        .HasColumnType("date");

                    b.HasKey("SubmissionId")
                        .HasName("PK__DonorSub__449EE125EC858707");

                    b.HasIndex("CampusId");

                    b.HasIndex("DonorId");

                    b.ToTable("DonorSubmission");
                });

            modelBuilder.Entity("PantryPlatoonMVCMain.Models.DonorSubmissionItem", b =>
                {
                    b.Property<int>("SubmissionItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubmissionItemId"));

                    b.Property<int?>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("SubmissionId")
                        .HasColumnType("int");

                    b.HasKey("SubmissionItemId")
                        .HasName("PK__DonorSub__BB8633974DEEFD61");

                    b.HasIndex("ItemId");

                    b.HasIndex("SubmissionId");

                    b.ToTable("DonorSubmissionItem");
                });

            modelBuilder.Entity("PantryPlatoonMVCMain.Models.Inventory", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventoryId"));

                    b.Property<int?>("CampusId")
                        .HasColumnType("int");

                    b.Property<int?>("ItemId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("InventoryId")
                        .HasName("PK__Inventor__F5FDE6B3F5E458C9");

                    b.HasIndex("CampusId");

                    b.HasIndex("ItemId");

                    b.ToTable("Inventory");
                });

            modelBuilder.Entity("PantryPlatoonMVCMain.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Points")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("ItemId")
                        .HasName("PK__Items__727E838BB912C500");

                    b.HasIndex("ItemCategoryId");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("PantryPlatoonMVCMain.Models.ItemCategory", b =>
                {
                    b.Property<int>("ItemCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemCategoryId"));

                    b.Property<string>("ItemCategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ItemCategoryId")
                        .HasName("PK__ItemCate__C24A2925B47D7986");

                    b.ToTable("ItemCategory");
                });

            modelBuilder.Entity("PantryPlatoonMVCMain.Models.StaticPage", b =>
                {
                    b.Property<int>("PageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PageId"));

                    b.Property<string>("HtmlContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PageName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PageId")
                        .HasName("PK__StaticPa__C565B104383F3B0F");

                    b.ToTable("StaticPages");
                });

            modelBuilder.Entity("PantryPlatoonMVCMain.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int?>("CampusId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SCCId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4C83F34527");

                    b.HasIndex("CampusId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("PantryPlatoonMVCMain.Models.Visit", b =>
                {
                    b.Property<int>("VisitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitId"));

                    b.Property<int?>("CampusId")
                        .HasColumnType("int");

                    b.Property<bool>("IsScheduledVisit")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ScheduledPickupTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("TotalWeight")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("VisitDate")
                        .HasColumnType("date");

                    b.HasKey("VisitId")
                        .HasName("PK__Visits__4D3AA1DEE3517811");

                    b.HasIndex("CampusId");

                    b.HasIndex("UserId");

                    b.ToTable("Visit");
                });

            modelBuilder.Entity("PantryPlatoonMVCMain.Models.VisitItem", b =>
                {
                    b.Property<int>("VisitItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitItemId"));

                    b.Property<int?>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityTaken")
                        .HasColumnType("int");

                    b.Property<int?>("VisitId")
                        .HasColumnType("int");

                    b.HasKey("VisitItemId")
                        .HasName("PK__VisitIte__4B99F797008F7E62");

                    b.HasIndex("ItemId");

                    b.HasIndex("VisitId");

                    b.ToTable("VisitItem");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PantryPlatoonMVCMain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PantryPlatoonMVCMain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PantryPlatoonMVCMain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PantryPlatoonMVCMain.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PantryPlatoonMVCMain.Models.DonorSubmission", b =>
                {
                    b.HasOne("PantryPlatoonMVCMain.Models.Campus", "Campus")
                        .WithMany("DonorSubmissions")
                        .HasForeignKey("CampusId")
                        .HasConstraintName("FK__DonorSubm__Campu__5DCAEF64");

                    b.HasOne("PantryPlatoonMVCMain.Models.User", "Donor")
                        .WithMany("DonorSubmissions")
                        .HasForeignKey("DonorId")
                        .HasConstraintName("FK__DonorSubm__Donor__5CD6CB2B");

                    b.Navigation("Campus");

                    b.Navigation("Donor");
                });

            modelBuilder.Entity("PantryPlatoonMVCMain.Models.DonorSubmissionItem", b =>
                {
                    b.HasOne("PantryPlatoonMVCMain.Models.Item", "Item")
                        .WithMany("DonorSubmissionItems")
                        .HasForeignKey("ItemId")
                        .HasConstraintName("FK__DonorSubm__ItemI__619B8048");

                    b.HasOne("PantryPlatoonMVCMain.Models.DonorSubmission", "Submission")
                        .WithMany("DonorSubmissionItems")
                        .HasForeignKey("SubmissionId")
                        .HasConstraintName("FK__DonorSubm__Submi__60A75C0F");

                    b.Navigation("Item");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("PantryPlatoonMVCMain.Models.Inventory", b =>
                {
                    b.HasOne("PantryPlatoonMVCMain.Models.Campus", "Campus")
                        .WithMany("Inventories")
                        .HasForeignKey("CampusId")
                        .HasConstraintName("FK__Inventory__Campu__5535A963");

                    b.HasOne("PantryPlatoonMVCMain.Models.Item", "Item")
                        .WithMany("Inventories")
                        .HasForeignKey("ItemId")
                        .HasConstraintName("FK__Inventory__ItemI__5441852A");

                    b.Navigation("Campus");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("PantryPlatoonMVCMain.Models.Item", b =>
                {
                    b.HasOne("PantryPlatoonMVCMain.Models.ItemCategory", "ItemCategory")
                        .WithMany("Items")
                        .HasForeignKey("ItemCategoryId")
                        .HasConstraintName("FK__Items__ItemCateg__5070F446");

                    b.Navigation("ItemCategory");
                });

            modelBuilder.Entity("PantryPlatoonMVCMain.Models.User", b =>
                {
                    b.HasOne("PantryPlatoonMVCMain.Models.Campus", "Campus")
                        .WithMany("Users")
                        .HasForeignKey("CampusId")
                        .HasConstraintName("FK__Users__CampusId__4BAC3F29");

                    b.Navigation("Campus");
                });

            modelBuilder.Entity("PantryPlatoonMVCMain.Models.Visit", b =>
                {
                    b.HasOne("PantryPlatoonMVCMain.Models.Campus", "Campus")
                        .WithMany("Visits")
                        .HasForeignKey("CampusId")
                        .HasConstraintName("FK__Visits__CampusId__59FA5E80");

                    b.HasOne("PantryPlatoonMVCMain.Models.User", "User")
                        .WithMany("Visits")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Visits__UserId__59063A47");

                    b.Navigation("Campus");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PantryPlatoonMVCMain.Models.VisitItem", b =>
                {
                    b.HasOne("PantryPlatoonMVCMain.Models.Item", "Item")
                        .WithMany("VisitItems")
                        .HasForeignKey("ItemId")
                        .HasConstraintName("FK__VisitItem__ItemI__6754599E");

                    b.HasOne("PantryPlatoonMVCMain.Models.Visit", "Visit")
                        .WithMany("VisitItems")
                        .HasForeignKey("VisitId")
                        .HasConstraintName("FK__VisitItem__Visit__66603565");

                    b.Navigation("Item");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("PantryPlatoonMVCMain.Models.Campus", b =>
                {
                    b.Navigation("DonorSubmissions");

                    b.Navigation("Inventories");

                    b.Navigation("Users");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("PantryPlatoonMVCMain.Models.DonorSubmission", b =>
                {
                    b.Navigation("DonorSubmissionItems");
                });

            modelBuilder.Entity("PantryPlatoonMVCMain.Models.Item", b =>
                {
                    b.Navigation("DonorSubmissionItems");

                    b.Navigation("Inventories");

                    b.Navigation("VisitItems");
                });

            modelBuilder.Entity("PantryPlatoonMVCMain.Models.ItemCategory", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("PantryPlatoonMVCMain.Models.User", b =>
                {
                    b.Navigation("DonorSubmissions");

                    b.Navigation("Visits");
                });

            modelBuilder.Entity("PantryPlatoonMVCMain.Models.Visit", b =>
                {
                    b.Navigation("VisitItems");
                });
#pragma warning restore 612, 618
        }
    }
}
